[package]
name = "router-echo"
version = "1.2.0"
edition = "2024"

[dependencies]
wit-bindgen = { workspace = true }
serde_json = { workspace = true }

[lib]
crate-type = ["cdylib"]

[package.metadata.component.target]
path = "wit"
world = "mcp-router"

[profile.release]
opt-level = "z"

[workspace]
